version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redddis
    volumes:
      - db_redis:/data
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass redddis

  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: wordpress/Dockerfile
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - redis
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: 'houssem'
      WORDPRESS_DB_PASSWORD: 'Hafidha_18'
      WORDPRESS_DB_NAME: 'trademarketnews'
      WORDPRESS_TABLE_PREFIX: ht_365m_
      WORDPRESS_CONFIG_EXTRA: |
        define('DISABLE_WP_CRON', true );
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/wp-content/plugins:/var/www/html/wp-content/plugins
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'trademarketnews'
      MYSQL_USER: 'houssem'
      MYSQL_PASSWORD: 'Hafidha_18'
      MYSQL_RANDOM_ROOT_PASSWORD: 'root_pass'
    volumes:
      - db_data:/var/lib/mysql
  nginx:
    container_name: nginx
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      VIRTUAL_HOST: "trademarketnews.com"
      VIRTUAL_PROTO: https
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  db_data:
  wordpress_data:
  db_redis:
  letsencrypt:
